apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: moc-ceph-tools

resources:
- deployment.yaml

configMapGenerator:
  - name: moc-scripts
    files:
      - scripts/config-ceph.py
